language: ruby
rvm:
- 2.3.1
script: bundle exec rake spec validate:attendees
before_install:
- openssl aes-256-cbc -K $encrypted_40a82c8f1ea5_key -iv $encrypted_40a82c8f1ea5_iv
  -in deploy_rsa.enc -out deploy_rsa -d