---
name: neinasaservice
web: 'http://unexpected-co.de'
avatar: 'https://secure.gravatar.com/avatar/8fb4c4eea4580647ac37881cec8606aa.png'
twitter: 'neinasaservice'
events:
  - year: 2012
    events:
     - 29c3
  - year: 2013
    events:
      - {name: "RailsGirls Aniversary Workshop", role: "Coach"}
      - eurucamp
      - GOTO Conference
  - year: 2014
    events:
      - wroclove.rb
      - republica
      - eurucamp
      - {name: "RailsGirls Workshop @ eurucamp", role: "Coach"}
      - railscamp
      - {name: "RailsGirls October Workshop", role: "Coach"}
      - Erlang Factory Lite
      - 31. Chaos Communication Congress
  - year: 2015
    events:
      - ROSSConf Vienna
