---
name: neinasaservice
web: 'http://unexpected-co.de'
avatar: 'https://secure.gravatar.com/avatar/8fb4c4eea4580647ac37881cec8606aa.png'
twitter: 'neinasaservice'
events:
  - 29c3
  - eurucamp 2013
  - GOTO Berlin 2013
  - wroclove.rb 2014
  - republica 2014
  - eurucamp 2014
  - railscamp 2014
